spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amir-academy-db
    username: postgres
    password: amir1124
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

upload:
  path: /upload